# preload = ~/.config/wallpapers/my_mountain.jpg
# preload = ~/.config/wallpapers/my_norway.jpeg

# wallpaper = 'HDMI-A-1', ~/.config/wallpapers/my_norway.jpeg
#
wallpaper {
    monitor =
    path = ~/.config/wallpapers/forest.png
    fit_mode = cover
}
splash = false # to not print a random quote in the bottom of the screen

